export const poem = [
  { 'name': '江南', 'author': '汉乐府', 'url': 'https://haitang.app/works/12069' },
  { 'name': '七律 · 长征', 'author': '现代 · 毛泽东', 'url': 'https://haitang.app/works/10073' },
  { 'name': '七步诗', 'author': '三国 · 魏 · 曹植', 'url': 'https://haitang.app/works/10104' },
  { 'name': '万安道中书事（其二）', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11059' },
  { 'name': '三衢道中', 'author': '宋 · 曾几', 'url': 'https://haitang.app/works/555752' },
  { 'name': '与史郎中钦听黄鹤楼上吹笛', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10979' },
  { 'name': '丑奴儿 · 书博山道中壁', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/10227' },
  { 'name': '临江仙', 'author': '明 · 杨慎', 'url': 'https://haitang.app/works/10220' },
  { 'name': '乌衣巷', 'author': '唐 · 刘禹锡', 'url': 'https://haitang.app/works/10173' },
  { 'name': '登乐游原', 'author': '唐 · 李商隐', 'url': 'https://haitang.app/works/10025' },
  { 'name': '九月九日忆山东兄弟', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10285' },
  { 'name': '乞巧', 'author': '唐 · 林杰', 'url': 'https://haitang.app/works/93241' },
  { 'name': '乡村四月', 'author': '宋 · 翁卷', 'url': 'https://haitang.app/works/11036' },
  { 'name': '书湖阴先生壁二首', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/10267' },
  { 'name': '二十四节气歌', 'author': '', 'url': '' },
  { 'name': '二月一日晓渡太和江', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11058' },
  { 'name': '二月十一日夜梦作东都早春绝句', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11045' },
  { 'name': '于易水送人', 'author': '唐 · 骆宾王', 'url': 'https://haitang.app/works/11974' },
  { 'name': '从军行', 'author': '唐 · 王昌龄', 'url': 'https://haitang.app/works/10186' },
  { 'name': '使至塞上', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10284' },
  { 'name': '元日', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/10266' },
  { 'name': '入常山界二首（其二）', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11056' },
  { 'name': '六月二十七日望湖楼醉书', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/11197' },
  { 'name': '关山月', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10490' },
  { 'name': '凉州词二首 · 其一', 'author': '唐 · 王之涣', 'url': 'https://haitang.app/works/10352' },
  { 'name': '凉州词二首 · 其一', 'author': '唐 · 王翰（子羽）', 'url': 'https://haitang.app/works/10411' },
  { 'name': '出塞', 'author': '唐 · 王昌龄', 'url': 'https://haitang.app/works/10185' },
  { 'name': '别董大（其一）', 'author': '唐 · 高适', 'url': 'https://haitang.app/works/10982' },
  { 'name': '前出塞', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/11150' },
  { 'name': '北山', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11022' },
  { 'name': '北陂杏花', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11132' },
  { 'name': '十二月十五夜', 'author': '清 · 袁枚', 'url': 'https://haitang.app/works/11041' },
  { 'name': '十五夜望月寄杜郎中', 'author': '唐 · 王建', 'url': 'https://haitang.app/works/10996' },
  { 'name': '华子冈', 'author': '唐 · 裴迪', 'url': 'https://haitang.app/works/10971' },
  { 'name': '南歌子', 'author': '宋 · 李清照', 'url': 'https://haitang.app/works/11072' },
  { 'name': '南歌子 · 钱塘端午', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/10462' },
  { 'name': '南溪弄水回望山园梅花', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11050' },
  { 'name': '南荡', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11020' },
  { 'name': '卜算子 · 咏梅', 'author': '宋 · 陆游', 'url': 'https://haitang.app/works/10048' },
  { 'name': '卜算子 · 咏梅', 'author': '现代 · 毛泽东', 'url': 'https://haitang.app/works/10062' },
  { 'name': '卜算子 · 送鲍浩然之浙东', 'author': '宋 · 王观', 'url': 'https://haitang.app/works/10737' },
  { 'name': '古文两则菊莲', 'author': '', 'url': '' },
  { 'name': '古朗月行', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/11751' },
  { 'name': '迢迢牵牛星', 'author': '汉 · 无名氏', 'url': 'https://haitang.app/works/10389' },
  { 'name': '台城', 'author': '唐 · 韦庄', 'url': 'https://haitang.app/works/11013' },
  { 'name': '听弹琴', 'author': '唐 · 刘长卿', 'url': 'https://haitang.app/works/10636' },
  { 'name': '咏柳', 'author': '唐 · 贺知章', 'url': 'https://haitang.app/works/11173' },
  { 'name': '咏鹅', 'author': '唐 · 骆宾王', 'url': 'https://haitang.app/works/10133' },
  { 'name': '喜见外弟又言别', 'author': '唐 · 李益', 'url': 'https://haitang.app/works/10453' },
  { 'name': '四时田园杂兴其三十一', 'author': '宋 · 范成大', 'url': 'https://haitang.app/works/480849' },
  { 'name': '四时田园杂兴其二十五', 'author': '宋 · 范成大', 'url': 'https://haitang.app/works/11032' },
  { 'name': '回乡偶书二首 · 其一', 'author': '唐 · 贺知章', 'url': 'https://haitang.app/works/10654' },
  { 'name': '国风 · 秦风 · 蒹葭', 'author': '周 · 无名氏', 'url': 'https://haitang.app/works/10963' },
  { 'name': '城东早春', 'author': '唐 · 杨巨源', 'url': 'https://haitang.app/works/10999' },
  { 'name': '塞下曲 · 其三', 'author': '唐 · 卢纶', 'url': 'https://haitang.app/works/10426' },
  { 'name': '塞下曲其二', 'author': '唐 · 卢纶', 'url': 'https://haitang.app/works/10037' },
  { 'name': '墨梅', 'author': '元 · 王冕', 'url': 'https://haitang.app/works/11039' },
  { 'name': '夏日绝句', 'author': '宋 · 李清照', 'url': 'https://haitang.app/works/10137' },
  { 'name': '夜书所见', 'author': '宋 · 叶绍翁', 'url': 'https://haitang.app/works/12003' },
  { 'name': '夜宿山寺', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10972' },
  { 'name': '夜雨寄北', 'author': '唐 · 李商隐', 'url': 'https://haitang.app/works/10024' },
  { 'name': '大林寺桃花', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/11007' },
  { 'name': '如梦令', 'author': '宋 · 李清照', 'url': 'https://haitang.app/works/10138' },
  { 'name': '如梦令 · 昨夜雨疏风骤', 'author': '宋 · 李清照', 'url': 'https://haitang.app/works/10139' },
  { 'name': '嫦娥', 'author': '唐 · 李商隐', 'url': 'https://haitang.app/works/10077' },
  { 'name': '定风波', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/10154' },
  { 'name': '宿建德江', 'author': '唐 · 孟浩然', 'url': 'https://haitang.app/works/10079' },
  { 'name': '宿新市徐公店', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11047' },
  { 'name': '寒食', 'author': '唐 · 韩翃', 'url': 'https://haitang.app/works/10659' },
  { 'name': '寻隐者不遇', 'author': '唐 · 贾岛', 'url': 'https://haitang.app/works/10644' },
  { 'name': '封舒国公（其二）', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11021' },
  { 'name': '小儿垂钓', 'author': '唐 · 胡令能', 'url': 'https://haitang.app/works/12083' },
  { 'name': '小池', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11052' },
  { 'name': '小雨', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11053' },
  { 'name': '山中', 'author': '唐 · 王勃', 'url': 'https://haitang.app/works/10967' },
  { 'name': '山中送别', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10969' },
  { 'name': '山亭夏日', 'author': '唐 · 高骈', 'url': 'https://haitang.app/works/11012' },
  { 'name': '山居秋暝', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10283' },
  { 'name': '山村', 'author': '宋 · 邵雍', 'url': 'https://haitang.app/works/11382' },
  { 'name': '山行', 'author': '唐 · 杜牧', 'url': 'https://haitang.app/works/10429' },
  { 'name': '山行留客', 'author': '唐 · 张旭', 'url': 'https://haitang.app/works/10968' },
  { 'name': '峨眉山月歌', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10978' },
  { 'name': '己亥杂诗 · 其五', 'author': '清 · 龚自珍', 'url': 'https://haitang.app/works/10308' },
  { 'name': '忆江南三首', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/11062' },
  { 'name': '悯农（其二）', 'author': '唐 · 李绅', 'url': 'https://haitang.app/works/11003' },
  { 'name': '悯农（其一）', 'author': '唐 · 李绅', 'url': 'https://haitang.app/works/11004' },
  { 'name': '惠崇春江晚景（其一）', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/11028' },
  { 'name': '感遇（其一）', 'author': '唐 · 张九龄', 'url': 'https://haitang.app/works/10463' },
  { 'name': '房兵曹胡马', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10988' },
  { 'name': '所见', 'author': '清 · 袁枚', 'url': 'https://haitang.app/works/11905' },
  { 'name': '敕勒歌', 'author': '北朝 · 民歌', 'url': 'https://haitang.app/works/10965' },
  { 'name': '旅夜书怀', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10357' },
  { 'name': '旅次朔方/渡桑干', 'author': '唐 · 刘皂', 'url': 'https://haitang.app/works/11009' },
  { 'name': '无题', 'author': '唐 · 李商隐', 'url': 'https://haitang.app/works/10327' },
  { 'name': '早发白帝城', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10210' },
  { 'name': '早春呈水部张十八员外二首（其一）', 'author': '唐 · 韩愈', 'url': 'https://haitang.app/works/11000' },
  { 'name': '早春对雪，寄前殿中元侍御', 'author': '唐 · 韦应物', 'url': 'https://haitang.app/works/10998' },
  { 'name': '春夜喜雨', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10355' },
  { 'name': '春夜洛城闻笛', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10975' },
  { 'name': '春日', 'author': '宋 · 朱熹', 'url': 'https://haitang.app/works/11033' },
  { 'name': '春日六绝句', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11044' },
  { 'name': '春日忆李白', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10989' },
  { 'name': '春晓', 'author': '唐 · 孟浩然', 'url': 'https://haitang.app/works/10078' },
  { 'name': '春暖郡圃散策三首（其三）', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11057' },
  { 'name': '春望', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10536' },
  { 'name': '春雪', 'author': '唐 · 韩愈', 'url': 'https://haitang.app/works/11002' },
  { 'name': '晓出净慈寺送林子方', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11051' },
  { 'name': '晚春二首（其一）', 'author': '唐 · 韩愈', 'url': 'https://haitang.app/works/11001' },
  { 'name': '暮江吟', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/11006' },
  { 'name': '月下独酌四首', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10209' },
  { 'name': '月夜', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10537' },
  { 'name': '月夜', 'author': '唐 · 刘方平', 'url': 'https://haitang.app/works/10660' },
  { 'name': '月夜忆舍弟', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10540' },
  { 'name': '望天门山', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10977' },
  { 'name': '望岳', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10095' },
  { 'name': '望庐山瀑布', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10974' },
  { 'name': '望月怀远', 'author': '唐 · 张九龄', 'url': 'https://haitang.app/works/10353' },
  { 'name': '望江南', 'author': '唐 · 温庭筠', 'url': 'https://haitang.app/works/11063' },
  { 'name': '望洞庭', 'author': '唐 · 刘禹锡', 'url': 'https://haitang.app/works/11689' },
  { 'name': '望湖楼晚景', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/11029' },
  { 'name': '杂诗', 'author': '唐 · 无名氏', 'url': 'https://haitang.app/works/10689' },
  { 'name': '杂诗三首', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10632' },
  { 'name': '村居', 'author': '清 · 高鼎', 'url': 'https://haitang.app/works/11043' },
  { 'name': '村晚', 'author': '宋 · 雷震', 'url': 'https://haitang.app/works/581119' },
  { 'name': '松江', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11026' },
  { 'name': '枫桥夜泊', 'author': '唐 · 张继', 'url': 'https://haitang.app/works/10270' },
  { 'name': '桂源铺', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11061' },
  { 'name': '梅花', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/10265' },
  { 'name': '水调歌头', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/10150' },
  { 'name': '江上', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11024' },
  { 'name': '江上渔者', 'author': '宋 · 范仲淹', 'url': 'https://haitang.app/works/11017' },
  { 'name': '江南春', 'author': '唐 · 杜牧', 'url': 'https://haitang.app/works/10454' },
  { 'name': '江南逢李龟年', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10423' },
  { 'name': '江村即事', 'author': '唐 · 司空曙', 'url': 'https://haitang.app/works/10993' },
  { 'name': '江村晚眺', 'author': '宋 · 戴复古', 'url': 'https://haitang.app/works/11037' },
  { 'name': '江畔独步寻花七绝句', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10986' },
  { 'name': '江行无题', 'author': '唐 · 钱珝', 'url': 'https://haitang.app/works/11016' },
  { 'name': '江雪', 'author': '唐 · 柳宗元', 'url': 'https://haitang.app/works/10196' },
  { 'name': '池上', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/12383' },
  { 'name': '泊秦淮', 'author': '唐 · 杜牧', 'url': 'https://haitang.app/works/10674' },
  { 'name': '泊船瓜洲', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/10269' },
  { 'name': '浣溪沙', 'author': '宋 · 周邦彦', 'url': 'https://haitang.app/works/11071' },
  { 'name': '浣溪沙 · 一向年光有限身', 'author': '宋 · 晏殊', 'url': 'https://haitang.app/works/11064' },
  { 'name': '浣溪沙 · 一曲新词酒一杯', 'author': '宋 · 晏殊', 'url': 'https://haitang.app/works/10707' },
  { 'name': '浣溪沙 · 漠漠轻寒上小楼', 'author': '宋 · 秦观', 'url': 'https://haitang.app/works/10323' },
  { 'name': '浪淘沙', 'author': '宋 · 欧阳修', 'url': 'https://haitang.app/works/10047' },
  { 'name': '浪淘沙', 'author': '唐 · 刘禹锡', 'url': 'https://haitang.app/works/111337' },
  { 'name': '浪淘沙令', 'author': '五代十国 · 李煜', 'url': 'https://haitang.app/works/10130' },
  { 'name': '淮上与友人别', 'author': '唐 · 郑谷', 'url': 'https://haitang.app/works/11015' },
  { 'name': '清平乐 · 村居', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/11074' },
  { 'name': '清平乐 · 独宿博山王氏庵', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/11079' },
  { 'name': '清明', 'author': '唐 · 杜牧', 'url': 'https://haitang.app/works/10428' },
  { 'name': '渔歌子 · 西塞山前白鹭飞', 'author': '唐 · 张志和', 'url': 'https://haitang.app/works/10191' },
  { 'name': '渔翁', 'author': '唐 · 柳宗元', 'url': 'https://haitang.app/works/10195' },
  { 'name': '游园不值', 'author': '宋 · 叶绍翁', 'url': 'https://haitang.app/works/11035' },
  { 'name': '游子吟', 'author': '唐 · 孟郊', 'url': 'https://haitang.app/works/10085' },
  { 'name': '游锺山', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11025' },
  { 'name': '湘口送友人', 'author': '唐 · 李频', 'url': 'https://haitang.app/works/10645' },
  { 'name': '滁州西涧', 'author': '唐 · 韦应物', 'url': 'https://haitang.app/works/10443' },
  { 'name': '满江红写怀', 'author': '宋 · 岳飞', 'url': 'https://haitang.app/works/10042' },
  { 'name': '独坐敬亭山', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10212' },
  { 'name': '玉楼春', 'author': '宋 · 欧阳修', 'url': 'https://haitang.app/works/11065' },
  { 'name': '生查子 · 独游雨岩', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/11077' },
  { 'name': '画', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/12445' },
  { 'name': '画眉鸟', 'author': '宋 · 欧阳修', 'url': 'https://haitang.app/works/11018' },
  { 'name': '画鸡', 'author': '明 · 唐寅', 'url': 'https://haitang.app/works/638347' },
  { 'name': '登乐游原', 'author': '唐 · 李商隐', 'url': 'https://haitang.app/works/10025' },
  { 'name': '登幽州台歌', 'author': '唐 · 陈子昂', 'url': 'https://haitang.app/works/10493' },
  { 'name': '登鹳雀楼', 'author': '唐 · 王之涣', 'url': 'https://haitang.app/works/10351' },
  { 'name': '百忧集行', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/84214' },
  { 'name': '盘古开天地', 'author': '', 'url': '' },
  { 'name': '相思', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10281' },
  { 'name': '相见欢', 'author': '五代十国 · 李煜', 'url': 'https://haitang.app/works/10131' },
  { 'name': '相见欢', 'author': '五代十国 · 李煜', 'url': 'https://haitang.app/works/10424' },
  { 'name': '石灰吟', 'author': '明 · 于谦', 'url': 'https://haitang.app/works/12367' },
  { 'name': '破阵子 · 为陈同甫赋壮词以寄之', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/10222' },
  { 'name': '示儿', 'author': '宋 · 陆游', 'url': 'https://haitang.app/works/11031' },
  { 'name': '秋夕', 'author': '唐 · 杜牧', 'url': 'https://haitang.app/works/10676' },
  { 'name': '秋夜寄丘二十二员外/秋夜寄邱员外', 'author': '唐 · 韦应物', 'url': 'https://haitang.app/works/10638' },
  { 'name': '秋夜将晓出篱门迎凉有感其二', 'author': '宋 · 陆游', 'url': 'https://haitang.app/works/11299' },
  { 'name': '秋思', 'author': '唐 · 张籍', 'url': 'https://haitang.app/works/10995' },
  { 'name': '秋思', 'author': '宋 · 陆游', 'url': 'https://haitang.app/works/11030' },
  { 'name': '秋浦歌', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/11973' },
  { 'name': '秋词（其一）', 'author': '唐 · 刘禹锡', 'url': 'https://haitang.app/works/10176' },
  { 'name': '移家别湖上亭', 'author': '唐 · 戎昱', 'url': 'https://haitang.app/works/10994' },
  { 'name': '稚子弄冰', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/571612' },
  { 'name': '竹枝词', 'author': '唐 · 刘禹锡', 'url': 'https://haitang.app/works/11124' },
  { 'name': '竹石', 'author': '清 · 郑燮', 'url': 'https://haitang.app/works/11042' },
  { 'name': '竹里馆', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10291' },
  { 'name': '约客/有约', 'author': '宋 · 赵师秀', 'url': 'https://haitang.app/works/11038' },
  { 'name': '绝句二首（其一）', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10983' },
  { 'name': '绝句二首（其二）', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10984' },
  { 'name': '绝句四首（其一）', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10985' },
  { 'name': '绝句四首 · 其三', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10099' },
  { 'name': '缚鸡行', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10991' },
  { 'name': '舟夜书所见', 'author': '清 · 查慎行', 'url': 'https://haitang.app/works/367303' },
  { 'name': '舟过安仁', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11049' },
  { 'name': '芙蓉楼送辛渐二首', 'author': '唐 · 王昌龄', 'url': 'https://haitang.app/works/10189' },
  { 'name': '花', 'author': '明 · 张羽', 'url': 'https://haitang.app/works/11040' },
  { 'name': '草/赋得古原草送别', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/10571' },
  { 'name': '菩萨蛮 · 金陵赏心亭为叶丞相赋', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/11080' },
  { 'name': '虞美人 · 春花秋月何时了', 'author': '五代十国 · 李煜', 'url': 'https://haitang.app/works/10128' },
  { 'name': '蜂', 'author': '唐 · 罗隐', 'url': 'https://haitang.app/works/11687' },
  { 'name': '蝉', 'author': '唐 · 虞世南', 'url': 'https://haitang.app/works/12067' },
  { 'name': '西江月 · 夜行黄沙道中', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/10031' },
  { 'name': '西江月 · 示儿曹，以家事付之', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/11076' },
  { 'name': '西江月 · 遣兴', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/11075' },
  { 'name': '观书有感', 'author': '宋 · 朱熹', 'url': 'https://haitang.app/works/10039' },
  { 'name': '观游鱼', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/11005' },
  { 'name': '诉衷情令', 'author': '宋 · 陆游', 'url': 'https://haitang.app/works/10417' },
  { 'name': '赋得古原草送别', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/10571' },
  { 'name': '赋新月', 'author': '唐 · 缪氏子', 'url': 'https://haitang.app/works/10992' },
  { 'name': '赠刘景文', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/630811' },
  { 'name': '赠外孙', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11023' },
  { 'name': '赠汪伦', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10976' },
  { 'name': '赠花卿', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10987' },
  { 'name': '赠范晔', 'author': '南北朝 · 陆凯', 'url': 'https://haitang.app/works/10966' },
  { 'name': '过故人庄', 'author': '唐 · 孟浩然', 'url': 'https://haitang.app/works/10551' },
  { 'name': '过零丁洋', 'author': '宋 · 文天祥', 'url': 'https://haitang.app/works/10260' },
  { 'name': '送元二使安西', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10287' },
  { 'name': '送友人', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10534' },
  { 'name': '送杜少府之任蜀州', 'author': '唐 · 王勃', 'url': 'https://haitang.app/works/10527' },
  { 'name': '送灵澈上人', 'author': '唐 · 刘长卿', 'url': 'https://haitang.app/works/10635' },
  { 'name': '逢入京使', 'author': '唐 · 岑参', 'url': 'https://haitang.app/works/10658' },
  { 'name': '逢雪宿芙蓉山主人', 'author': '唐 · 刘长卿', 'url': 'https://haitang.app/works/10460' },
  { 'name': '道旁竹', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11046' },
  { 'name': '遗爱寺', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/635557' },
  { 'name': '采桑子', 'author': '宋 · 欧阳修', 'url': 'https://haitang.app/works/11066' },
  { 'name': '采桑子', 'author': '宋 · 欧阳修', 'url': 'https://haitang.app/works/10754' },
  { 'name': '采桑子', 'author': '宋 · 欧阳修', 'url': 'https://haitang.app/works/11069' },
  { 'name': '采桑子', 'author': '宋 · 欧阳修', 'url': 'https://haitang.app/works/11070' },
  { 'name': '采桑子 · 何人解赏西湖好', 'author': '宋 · 欧阳修', 'url': 'https://haitang.app/works/11068' },
  { 'name': '采莲曲二首 · 其二', 'author': '唐 · 王昌龄', 'url': 'https://haitang.app/works/11205' },
  { 'name': '采薇', 'author': '诗经(小雅 · 采薇节选)', 'url': 'https://haitang.app/works/11087' },
  { 'name': '钱塘湖春行', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/10455' },
  { 'name': '长干行', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10211' },
  { 'name': '长干行其一', 'author': '唐 · 崔颢', 'url': 'https://haitang.app/works/10648' },
  { 'name': '长歌行', 'author': '汉乐府', 'url': 'https://haitang.app/works/10394' },
  { 'name': '长相思 · 山一程水一程', 'author': '清 · 纳兰性德', 'url': 'https://haitang.app/works/10120' },
  { 'name': '问刘十九', 'author': '唐 · 白居易', 'url': 'https://haitang.app/works/10020' },
  { 'name': '闲居初夏午睡起二绝句（其一）', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11054' },
  { 'name': '闲居初夏午睡起二绝句（其二）', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11055' },
  { 'name': '闻官军收河南河北', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10100' },
  { 'name': '闻王昌龄左迁龙标遥有此寄', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10973' },
  { 'name': '陇西行四首（其二）', 'author': '唐 · 陈陶', 'url': 'https://haitang.app/works/10413' },
  { 'name': '除架', 'author': '唐 · 杜甫', 'url': 'https://haitang.app/works/10990' },
  { 'name': '雨后田间杂纪（其二）', 'author': '宋 · 杨万里', 'url': 'https://haitang.app/works/11048' },
  { 'name': '雨晴', 'author': '唐 · 王驾', 'url': 'https://haitang.app/works/11014' },
  { 'name': '雪梅', 'author': '宋 · 卢钺', 'url': 'https://haitang.app/works/11191' },
  { 'name': '雪梅', 'author': '宋 · 卢钺', 'url': 'https://haitang.app/works/11192' },
  { 'name': '零陵早春', 'author': '唐 · 柳宗元', 'url': 'https://haitang.app/works/11008' },
  { 'name': '霜天晓角', 'author': '宋 · 蒋捷', 'url': 'https://haitang.app/works/11081' },
  { 'name': '霜月', 'author': '唐 · 李商隐', 'url': 'https://haitang.app/works/11011' },
  { 'name': '静夜思', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10156' },
  { 'name': '题三闾大夫庙', 'author': '唐 · 戴叔伦', 'url': 'https://haitang.app/works/10997' },
  { 'name': '题临安邸', 'author': '宋 · 林升', 'url': 'https://haitang.app/works/11034' },
  { 'name': '题何氏宅园亭', 'author': '宋 · 王安石', 'url': 'https://haitang.app/works/11019' },
  { 'name': '题西林壁', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/10151' },
  { 'name': '题都城南庄', 'author': '唐 · 崔护', 'url': 'https://haitang.app/works/10316' },
  { 'name': '风', 'author': '唐 · 李峤', 'url': 'https://haitang.app/works/85388' },
  { 'name': '饮湖上初晴后雨（其二）', 'author': '宋 · 苏轼', 'url': 'https://haitang.app/works/11027' },
  { 'name': '饮酒（其五）', 'author': '晋 · 陶渊明', 'url': 'https://haitang.app/works/10030' },
  { 'name': '饮酒（其四）', 'author': '晋 · 陶渊明', 'url': 'https://haitang.app/works/10964' },
  { 'name': '马诗', 'author': '唐 · 李贺', 'url': 'https://haitang.app/works/11590' },
  { 'name': '鸟鸣涧', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10282' },
  { 'name': '鹧鸪天 · 博山寺作', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/11073' },
  { 'name': '鹧鸪天 · 鹅湖归，病起作', 'author': '宋 · 辛弃疾', 'url': 'https://haitang.app/works/10857' },
  { 'name': '鹿柴', 'author': '唐 · 王维', 'url': 'https://haitang.app/works/10631' },
  { 'name': '黄鹤楼', 'author': '唐 · 崔颢', 'url': 'https://haitang.app/works/10350' },
  { 'name': '黄鹤楼送孟浩然之广陵', 'author': '唐 · 李白', 'url': 'https://haitang.app/works/10657' }
]